### PR TITLE
State explicitly that our current maximal length of the path in dandiset must no exceed 512

### PR DESCRIPTION
**Pull request by yarikoptic**
ATM, if my check is right -- maximal length we can encounter is only 192, so we are quite ok

	dandi@drogon:/mnt/backup/dandi/dandisets$ pwd
	/mnt/backup/dandi/dandisets

	dandi@drogon:/mnt/backup/dandi/dandisets$ declare m=0;for ds in 00*; do git -C $ds ls-tree -r --name-only HEAD; done | awk '{ if (length($0) > max) max = length($0) } END { print max }'
	192

When user manages to get over -- server 500s. Filed 
- https://github.com/dandi/dandi-archive/issues/1889

### CODE REVIEW

**Comment by satra** [comment]
we don't put dandi nwb inspector or schema constraints in the policy document. is this really something for a policy change? also if this is a policy change, the policy version should be incremented. 

i would say this is out of scope for policy.

**Review by satra — COMMENTED** [review]
see comments

**Comment by yarikoptic** [comment]
It has nothing to do with nwb and inspectors. See the issue I linked in the archive - it is our current coded in technical limitation similarly to max file size on s3.

**Comment by yarikoptic** [comment]
per discussion on slack -- moved both into another document from Policy and boosted policy version.

**Review by satra — APPROVED** [review]

**Pull request merged**
