### PR TITLE
[wip] website usage

### PR DESCRIPTION
**Pull request by djarecka**
I've added more info about dandi web and how to use it. (still have to add part on dandiset creation).

I'm not sure if this should stay in this one document. Perhaps we could have a separate documents for more detailed info regarding web, dandic-cli, etc.? Please share your thoughts.

### CODE REVIEW

**Comment by satra** [comment]
a separate page would be good and you can link that to the using dandi page.

**Comment by satra** [comment]
@djarecka - this looks great. should we update the two DLP figures to reflect the new DLP that was merged?

**Comment by djarecka** [comment]
sure, can do it

**Comment by djarecka** [comment]
I believe I updated everything what has changed

**Pull request merged**
