### PR TITLE
Refactor "Developer Guide" into a single doc + include TOC into navigation

### PR DESCRIPTION
**Pull request by yarikoptic**
Decided to include both commits in one PR since it better demonstrate difference in appearance for the first commit change of including TOC within navigation bar on the left (instead of adding it on the right). E.g. how it would look with current RF of the Guide and 

<details>
<summary>webshots</summary>

image

instead of old one

image

and here is how it looks now (note that TOC is not available due to `#` section on top of the file):

image

</details>

But if so not desired (I thought it is nice since avoids wild runs of mouse from the left to right, and gives more width for text), I can just drop that commit from the PR.

2nd commit is more profound:  I found that we had pretty much multiple points describing components with very overlapping amount of detail between https://www.dandiarchive.org/handbook/20_project_structure/ , https://www.dandiarchive.org/handbook/40_development/#overview and then subsections therein like https://www.dandiarchive.org/handbook/40_development/#technologies-used .  So , because they all are placed under "Developer Guide" I just decided to keep it only in 40_development, make it the "Developer Guide" and there structure via sections, not just itemized list, into components.  That gives more space to describe each component and provide subsections like we do for `dandi-archive` under which I placed now relevant (only) to it other sections (Deployment and Technologies).

If overall flow is ok, I would then (in this PR or follow up) would like to add a section on other common principles we would like to harmonize **across** components e.g. Pull Requests - who merges/closes comments/etc.

### CODE REVIEW

**Comment by melster1010** [comment]
I definitely prefer having all the TOC links all on the left side.

I had moved the schematic figure to docs/20_project_structure.md in my current PR, but this file is deleted as part of this PR. Need to sort that out.

**Review by satra — COMMENTED** [review]
this needs a fair bit of refactoring.

- start with an overview of components (perhaps a version of [this figure](https://docs.google.com/presentation/d/1hqw0vgNmelNnkPLuCSA1L5Rlu2rXeZEF6bsgc0y6Ve4/edit#slide=id.g1431119c946_0_5) ) and their roles.
- general developer guidelines
  - how to contribute etc.,. or pointers to CONTRIBUTING.md
  - the current section starts with helpdesk. do you want developers to use the helpdesk or directly go to project issues? 
- for each component/group of components provide developer guidelines of how to install/run etc.,.

**Comment by yarikoptic** [comment]
@satra -- those are not just "a fair bit" but rather substantial further refactoring. 
I personally would not have time for it ATM. So, we can leave it as is now (IMHO suboptimal since prompted this PR due to extensive duplication and TOC visualization) or accept this PR as a step forward and then address those issues you raised in separate follow up PRs.

**Comment by yarikoptic** [comment]
we have an alternative RFing of development guide... i might bring TOC later separately

**Pull request closed without merging**
