### PR TITLE
Use smaller size of the banner to make page load faster

### PR DESCRIPTION
**Pull request by yarikoptic**
ATM my connection was a bit saturated with other stuff, and loading of this documentation page was very slow as the banner slowlly appeared...  Apparently it is 1MB in size since almost 6k in width... I made a smaller copy which takes 6x times less and recommend we use that one - no need to waste bandwidth

	❯ file docs/img/dandi-banner*png
	docs/img/dandi-banner.png:       PNG image data, 5938 x 2188, 8-bit/color RGBA, non-interlaced
	docs/img/dandi-banner-small.png: PNG image data, 1024 x 377, 8-bit/color RGBA, non-interlaced

	❯ ls -ld docs/img/dandi-banner*png
	-rw------- 1 yoh yoh  69197 Jul  5 09:00 docs/img/dandi-banner-small.png
	-rw------- 1 yoh yoh 463441 Aug  5  2020 docs/img/dandi-banner.png

### CODE REVIEW

**Comment by satra** [comment]
didn't @TheChymera  create a different version. we should perhaps use that?

**Review by waxlamp — APPROVED** [review]
This looks good to me, but a couple of recommendations (should you choose to accept them in place of this PR):
- Satra's thing about whether Horea has a better version of this banner
- Remove the larger banner file

**Comment by yarikoptic** [comment]
Let's proceed with #88 although it reduces only by 45% so still has that image too large imho than necessary. Someone would eventually get a proper SVG for it. May be @satra remembers how this image came about and either it had some proper vector version of it?

**Comment by TheChymera** [comment]
@yarikoptic I already have a proper SVG → https://github.com/dandi/artwork/blob/master/pics/dandi-banner.svg

Sorry for the confusion, I just thought we keep this stuff in its dedicated repo...

Perhaps to fix this, should we make that repo a submodule for this one?

Also, there's a related PR over there which updates the rasterized PNG https://github.com/dandi/artwork/pull/2

**Pull request closed without merging**
